# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstFriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstFriend', to=settings.AUTH_USER_MODEL)),
                ('secondFriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondFriend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
